Moocs Spider
Open-Edu-Tw/Scraper pull request #4
Opened 2021-12-20 15:00 UTC by mohsu

68 pages, 1211 courses

2021-12-20 15:02 UTC, pan93412 requested changes

2021-12-20 15:02 UTC, pan93412 commented on ocw/spiders/moocs.py
> +                                 source="磨客師")
typo? https://taiwanmooc.org/

2021-12-20 15:05 UTC, mohsu commented on ocw/spiders/moocs.py
> +                                 source="磨客師")
which one

2021-12-20 15:07 UTC, mohsu commented on ocw/spiders/moocs.py
> +                                 source="磨客師")
moocs?

2021-12-20 23:04 UTC, pan93412 commented on ocw/spiders/moocs.py
> +                                 source="磨客師")
> moocs?

MOOCs，Massive Open Online Courses，又稱為「磨課師」，也就是「大規模開放式線上課程」，透過網路，把課程開放給大量線上使用者參與學習過程。

然後你打成「磨 **客** 師」

2021-12-21 01:04 UTC, mohsu commented on ocw/spiders/moocs.py
> +                                 source="磨客師")
哦!!!!! 一直沒看到 3Q~~~

2021-12-21 01:05 UTC, mohsu commented on ocw/spiders/moocs.py
> +                                 source="磨客師")
那我也改成MOOC

2021-12-21 02:07 UTC, pan93412 requested changes
檔名也建議改掉

2021-12-23 15:22 UTC, merged